CREATE TABLE product (
    id INT AUTO_INCREMENT PRIMARY KEY,
    product_id VARCHAR(255) UNIQUE,
    bleaching_code INT,
    default_language VARCHAR(10),
    sap_packet INT,
    update_images BOOLEAN,
    dry_cleaning_code INT,
    drying_code INT,
    fastening_type_code INT,
    ironing_code INT,
    pullout_type_code INT,
    waistline_code INT,
    washability_code INT
);


CREATE TABLE header_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_product VARCHAR(255),
    bag BOOLEAN,
    bleaching_description TEXT,
    brand VARCHAR(100),
    brand_code INT,
    catalog VARCHAR(100),
    composition TEXT,
    creation_date DATETIME,
    drink_holder BOOLEAN,
    dry_cleaning_description TEXT,
    drying_description TEXT,
    e_shop_display_name VARCHAR(255),
    e_shop_long_description TEXT,
    ergonomic_seat BOOLEAN,
    fastening_type_description TEXT,
    fastening_type_textile TEXT,
    flat BOOLEAN,
    free_delivery BOOLEAN,
    gender VARCHAR(50),
    indicator_of_it_has_to_be_assembled BOOLEAN,
    ironing_description TEXT,
    last_date_changed DATETIME,
    last_user_changed VARCHAR(50),
    sap_category_id VARCHAR(10),
    sap_category_name VARCHAR(100),
    sap_division_id VARCHAR(10),
    sap_division_name VARCHAR(100),
    sap_family_description TEXT,
    sap_family_id VARCHAR(10),
    sap_family_name VARCHAR(100),
    sap_macrocategory_id VARCHAR(10),
    sap_macrocategory_name VARCHAR(100),
    sap_name VARCHAR(255),
    sap_universe_id VARCHAR(10),
    sap_universe_name VARCHAR(100),
    show_online BOOLEAN,
    size_guide VARCHAR(50),
    user_of_creation VARCHAR(50),
    waistline_description TEXT,
    washability TEXT,
    washability_description TEXT,
    zip_stopper BOOLEAN,
    FOREIGN KEY (id_product) REFERENCES product(product_id) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE details_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_product  varchar(255),
    cedi VARCHAR(10),
    child_weight_from DECIMAL(10, 2),
    child_weight_to DECIMAL(10, 2),
    color_code VARCHAR(10),
    color_description VARCHAR(255),
    country_images BOOLEAN,
    default_sku BOOLEAN,
    preferred_ean VARCHAR(20),
    sap_assortment_level VARCHAR(10),
    sap_price DECIMAL(10, 2),
    season VARCHAR(10),
    show_online_sku BOOLEAN,
    size_code VARCHAR(10),
    size_description VARCHAR(255),
    sku_id VARCHAR(20) UNIQUE,
    sku_name VARCHAR(255),
    state_of_article BOOLEAN,
    um_sap_price VARCHAR(5),
    volume DECIMAL(10, 2),
    weight DECIMAL(10, 2),
    FOREIGN KEY (id_product) REFERENCES product(product_id) ON DELETE CASCADE ON UPDATE CASCADE
);
